/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 06-May-2016 04:19:55
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
const int BL = 29;
const real64_T B[29] = {
  -0.001996658209702, -0.01355533129237,  -0.0147659450395, -0.02025397484271,
   -0.02242479985578, -0.02051387955141, -0.01287630088156, 0.001204954545784,
    0.02145429169875,  0.04644767293082,  0.07368823906657,  0.09997333433724,
     0.1219005164783,    0.136448190977,   0.1415424741135,    0.136448190977,
     0.1219005164783,  0.09997333433724,  0.07368823906657,  0.04644767293082,
    0.02145429169875, 0.001204954545784, -0.01287630088156, -0.02051387955141,
   -0.02242479985578, -0.02025397484271,  -0.0147659450395, -0.01355533129237,
  -0.001996658209702
};
